# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lwp_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(858, 536)
        Form.setStyleSheet("*{\n"
"    font-family: 微软雅黑;\n"
"    font-size: 14pt;\n"
"    background-color: none;\n"
"}\n"
"\n"
"QWidget#Form{\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 0px;\n"
"    border-bottom: 2px solid black;\n"
"    padding: 3px 7px;\n"
"    background-color: #f6f8fa;\n"
"}\n"
"\n"
"QLabel{\n"
"    font-size: 12pt;\n"
"    color: grey;\n"
"}\n"
"\n"
"QLabel#labelLwpVer{\n"
"    font-size: 8pt;\n"
"    color: grey;\n"
"    border-radius: 7px;\n"
"    border: 1px solid grey;\n"
"    padding: 1px 5px;\n"
"}\n"
"\n"
"QGroupBox{\n"
"    border-radius: 10px;\n"
"    background-color: #E6ECF2;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QGroupBox#groupBoxItemContent{\n"
"    border-radius: 10px;\n"
"    background-color: #f6f8fa;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QRadioButton{\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QTextEdit{\n"
"    border: 3px solid #f6f8fa;\n"
"    border-radius: 10px;\n"
"    padding: 7px;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.labelPic = QtWidgets.QLabel(Form)
        self.labelPic.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPic.setObjectName("labelPic")
        self.horizontalLayout_5.addWidget(self.labelPic)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButtonJRJA = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonJRJA.setObjectName("radioButtonJRJA")
        self.horizontalLayout_3.addWidget(self.radioButtonJRJA)
        self.radioButtonPayload = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonPayload.setObjectName("radioButtonPayload")
        self.horizontalLayout_3.addWidget(self.radioButtonPayload)
        self.radioButtonMac = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonMac.setObjectName("radioButtonMac")
        self.horizontalLayout_3.addWidget(self.radioButtonMac)
        self.horizontalLayout_2.addWidget(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem3)
        self.labelLwpVer = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLwpVer.sizePolicy().hasHeightForWidth())
        self.labelLwpVer.setSizePolicy(sizePolicy)
        self.labelLwpVer.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLwpVer.setObjectName("labelLwpVer")
        self.verticalLayout_7.addWidget(self.labelLwpVer)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBoxItemContent = QtWidgets.QGroupBox(Form)
        self.groupBoxItemContent.setTitle("")
        self.groupBoxItemContent.setObjectName("groupBoxItemContent")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBoxItemContent)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.groupBoxItemContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.lineEditJoinRequest = QtWidgets.QLineEdit(self.page_4)
        self.lineEditJoinRequest.setObjectName("lineEditJoinRequest")
        self.verticalLayout_6.addWidget(self.lineEditJoinRequest)
        self.label_5 = QtWidgets.QLabel(self.page_4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.lineEditJoinAnswer = QtWidgets.QLineEdit(self.page_4)
        self.lineEditJoinAnswer.setObjectName("lineEditJoinAnswer")
        self.verticalLayout_6.addWidget(self.lineEditJoinAnswer)
        self.label_6 = QtWidgets.QLabel(self.page_4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.lineEditAppkey = QtWidgets.QLineEdit(self.page_4)
        self.lineEditAppkey.setObjectName("lineEditAppkey")
        self.verticalLayout_6.addWidget(self.lineEditAppkey)
        self.stackedWidget.addWidget(self.page_4)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.lineEditAppskey = QtWidgets.QLineEdit(self.page_2)
        self.lineEditAppskey.setObjectName("lineEditAppskey")
        self.verticalLayout_4.addWidget(self.lineEditAppskey)
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.lineEditNwkskey = QtWidgets.QLineEdit(self.page_2)
        self.lineEditNwkskey.setObjectName("lineEditNwkskey")
        self.verticalLayout_4.addWidget(self.lineEditNwkskey)
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.lineEditPayload = QtWidgets.QLineEdit(self.page_2)
        self.lineEditPayload.setObjectName("lineEditPayload")
        self.verticalLayout_4.addWidget(self.lineEditPayload)
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButtonUplink = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonUplink.setObjectName("radioButtonUplink")
        self.horizontalLayout_4.addWidget(self.radioButtonUplink)
        self.radioButtonDownlink = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonDownlink.setObjectName("radioButtonDownlink")
        self.horizontalLayout_4.addWidget(self.radioButtonDownlink)
        self.horizontalLayout.addWidget(self.groupBox_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.page)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.lineEditMaccmd = QtWidgets.QLineEdit(self.page)
        self.lineEditMaccmd.setObjectName("lineEditMaccmd")
        self.verticalLayout_3.addWidget(self.lineEditMaccmd)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.page)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.groupBoxItemContent)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.textEditAck = QtWidgets.QTextEdit(Form)
        self.textEditAck.setObjectName("textEditAck")
        self.verticalLayout.addWidget(self.textEditAck)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelPic.setText(_translate("Form", "-"))
        self.radioButtonJRJA.setText(_translate("Form", "解析入网请求/应答"))
        self.radioButtonPayload.setText(_translate("Form", "解析Payload"))
        self.radioButtonMac.setText(_translate("Form", "解析Mac指令"))
        self.labelLwpVer.setText(_translate("Form", "-"))
        self.label_4.setText(_translate("Form", "入网请求Join Request"))
        self.label_5.setText(_translate("Form", "入网应答Join Answer"))
        self.label_6.setText(_translate("Form", "APPKEY"))
        self.label_2.setText(_translate("Form", "APPSKEY"))
        self.label_3.setText(_translate("Form", "NWKSKEY"))
        self.label_7.setText(_translate("Form", "待解析协议层数据(PAYLOAD)"))
        self.radioButtonUplink.setText(_translate("Form", "节点->服务器"))
        self.radioButtonDownlink.setText(_translate("Form", "服务器->节点"))
        self.label.setText(_translate("Form", "待解析MAC指令数据"))
        self.label_8.setText(_translate("Form", "解析结果"))
